"""Refactor Token model and User relation

Revision ID: 562d15205271
Revises: 
Create Date: 2025-12-27 08:41:21.485685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562d15205271'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('token_type', sa.Enum('ACCESS', 'REFRESH', name='tokentype'), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.u_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_token_id'), 'tbl_token', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_token_token'), 'tbl_token', ['token'], unique=True)
    op.drop_index('idx_users_uid', table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_constraint('users_u_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_u_id'), 'users', ['u_id'], unique=False)
    op.create_index(op.f('ix_users_u_username'), 'users', ['u_username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_u_username'), table_name='users')
    op.drop_index(op.f('ix_users_u_id'), table_name='users')
    op.create_unique_constraint('users_u_username_key', 'users', ['u_username'])
    op.create_index('idx_users_username', 'users', ['u_username'], unique=False)
    op.create_index('idx_users_uid', 'users', ['u_id'], unique=False)
    op.drop_index(op.f('ix_tbl_token_token'), table_name='tbl_token')
    op.drop_index(op.f('ix_tbl_token_id'), table_name='tbl_token')
    op.drop_table('tbl_token')
    # ### end Alembic commands ###
